export const products=[
  {
    id:1,
    name:'Café Tostado Molido',
    price: 35000,
    weight:'250 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
  {
    id:2,
    name:'Café Tostado Molido',
    price: 68000,
    weight:'500 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
  {
    id:3,
    name:'Café Tostado Molido',
    price: 98000,
    weight:'1000 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
  {
    id:4,
    name:'Café Tostado en Grano',
    price: 35000,
    weight:'250 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
  {
    id:5,
    name:'Café Tostado en Grano',
    price: 68000,
    weight:'500 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
  {
    id:6,
    name:'Café Tostado en Grano',
    price: 98000,
    weight:'1000 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
  {
    id:7,
    name:'Granos de Café Seco',
    price: 32000,
    weight:'250 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
  {
    id:8,
    name:'Granos de Café Seco',
    price: 60000,
    weight:'500 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
  {
    id:9,
    name:'Granos de Café Seco',
    price: 92000,
    weight:'1000 Gr',
    image: 'coffe_bag.svg',
    available: true,
    amount: 1,
  },
 
 
];